export { default as EditProfileImg } from "./EditProfileImg";
export { default as MenuList } from "./MenuList";
export { default as PrimaryModal } from "./PrimaryModal";
export { default as StudiousLogoParallel } from "./StudiousLogoParallel";
export { default as StudiousLogoVertical } from "./StudiousLogoVertical";
export { default as IconWithName } from "./IconWithName";
export { default as ImgModal } from "./ImgModal";
export { default as InputTime } from "./InputTime";
export { default as PrimaryText } from "./PrimaryText";
